version: '3'
services:
  proxy:
    build: proxy/
    links:
      - freecoin
    ports:
      - 2000:2000
  freecoin:
    build: .
    container_name: freecoin
    links:
      - db
    command: "/app/bin/lein ring server-headless"
    volumes:
      - "./faircoin/config:/faircoin/config"
      - "./project.clj:/app/src/project.clj"
  db:
    image: mongo
    ports:
      - "27017:27017"